on:
  pull_request:
    paths: 
      - "**.go"
      - go.mod
      - go.sum
      - .github/workflows/lint-test.yml
      - docstak.md
  workflow_dispatch:
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum
      - name: docstak/install
        run: go install ./cmd/docstak
      - name: docstak/ci-lint
        run: docstak ci-lint-test
      